[package]
name = "haversine_generator"
version = "0.1.0"
edition = "2024"

[features]
measure_timer_frequency = []
profiler = []

[[bin]]
name = "generator"

[dependencies]
rand = "0.9.1"
rand_xoshiro = "0.7.0"
libc = "0.2"
cfg-if = "1.0"
insta = "1.43.1"

[build-dependencies]
cc = "1"
